"""SQLAlchemy declarative base + shared mixins."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.common.ids import new_id


class Base(DeclarativeBase):
    """Application declarative base."""


def _utcnow() -> datetime:
    return datetime.now(tz=timezone.utc)


class UUIDPKMixin:
    """UUID primary key.

    Uses SQLAlchemy 2.x `Uuid` type: native UUID on Postgres, CHAR(32) on
    SQLite. Default is generated by the application (see `common/ids.py`) so
    tests work without server-side UUID functions.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=new_id,
    )


class TimestampMixin:
    """created_at / updated_at with UTC-aware timestamps.

    On Postgres these map to TIMESTAMPTZ. On SQLite (tests only) the timezone
    is stripped by the driver; we compensate in application code where it
    matters. Timestamps are always written in UTC.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
        server_default=func.now(),
    )
